//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analytic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Analytic()
        {
            this.DepartmentsId = 1;
            this.TimeSheetTable = new HashSet<TimeSheetTable>();
        }
    
        public int Id { get; set; }
        public string userName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public int DepartmentsId { get; set; }
        public int DirectionsId { get; set; }
        public int UpravlenieTableId { get; set; }
        public int OtdelTableId { get; set; }
        public int PositionsId { get; set; }
        public int RoleTableId { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Directions Directions { get; set; }
        public virtual UpravlenieTable Upravlenie { get; set; }
        public virtual OtdelTable Otdel { get; set; }
        public virtual Positions Positions { get; set; }
        public virtual RoleTable Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSheetTable> TimeSheetTable { get; set; }
    }
}
