//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeSheetDBEntities : DbContext
    {
        public TimeSheetDBEntities()
            : base("name=TimeSheetDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Analytic> Analytic { get; set; }
        public virtual DbSet<TimeSheetTable> TimeSheetTable { get; set; }
        public virtual DbSet<Block> Block { get; set; }
        public virtual DbSet<BusinessBlock> BusinessBlock { get; set; }
        public virtual DbSet<ClientWays> ClientWays { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Escalations> Escalations { get; set; }
        public virtual DbSet<ForceQuit> ForceQuit { get; set; }
        public virtual DbSet<Formats> Formats { get; set; }
        public virtual DbSet<OtdelTable> OtdelTable { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Process> Process { get; set; }
        public virtual DbSet<ProcessType> ProcessType { get; set; }
        public virtual DbSet<Result> Result { get; set; }
        public virtual DbSet<riskChoise> riskChoise { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<SubBlock> SubBlock { get; set; }
        public virtual DbSet<Supports> Supports { get; set; }
        public virtual DbSet<UpravlenieTable> UpravlenieTable { get; set; }
        public virtual DbSet<Directions> DirectionsSet { get; set; }
        public virtual DbSet<Risk> RiskSet { get; set; }
        public virtual DbSet<supportChoice> supportChoiceSet { get; set; }
        public virtual DbSet<EscalationChoice> EscalationChoiceSet { get; set; }
        public virtual DbSet<BusinessBlockChoice> BusinessBlockChoiceSet { get; set; }
    }
}
