//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EscalationChoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EscalationChoice()
        {
            this.TimeSheetTable = new HashSet<TimeSheetTable>();
        }
    
        public int id { get; set; }
        public Nullable<int> Escalation_id { get; set; }
        public Nullable<int> Escalation_id1 { get; set; }
        public Nullable<int> Escalation_id2 { get; set; }
        public Nullable<int> Escalation_id3 { get; set; }
        public Nullable<int> Escalation_id4 { get; set; }
        public Nullable<int> Escalation_id5 { get; set; }
        public Nullable<int> Escalation_id6 { get; set; }
        public Nullable<int> Escalation_id7 { get; set; }
        public Nullable<int> Escalation_id8 { get; set; }
        public Nullable<int> Escalation_id9 { get; set; }
        public Nullable<int> Escalation_id10 { get; set; }
        public Nullable<int> Escalation_id11 { get; set; }
        public Nullable<int> Escalation_id12 { get; set; }
        public Nullable<int> Escalation_id13 { get; set; }
        public Nullable<int> Escalation_id14 { get; set; }
        public Nullable<int> Escalation_id15 { get; set; }
    
        public virtual Escalations Escalations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSheetTable> TimeSheetTable { get; set; }
    }
}
