//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Process
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Process()
        {
            this.SubBlockId = 1;
            this.TimeSheetTable = new HashSet<TimeSheetTable>();
        }
    
        public int id { get; set; }
        public string procName { get; set; }
        public string Comment { get; set; }
        public Nullable<bool> CommentNeeded { get; set; }
        public int Block_id { get; set; }
        public int SubBlockId { get; set; }
        public int ProcessType_id { get; set; }
        public int Result_id { get; set; }
    
        public virtual Block Block1 { get; set; }
        public virtual SubBlock SubBlockNav { get; set; }
        public virtual ProcessType ProcessType1 { get; set; }
        public virtual Result Result1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSheetTable> TimeSheetTable { get; set; }
    }
}
