//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeSheetApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class riskChoise
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public riskChoise()
        {
            this.TimeSheetTable = new HashSet<TimeSheetTable>();
        }
    
        public int id { get; set; }
        public Nullable<int> Risk_id { get; set; }
        public Nullable<int> Risk_id1 { get; set; }
        public Nullable<int> Risk_id2 { get; set; }
        public Nullable<int> Risk_id3 { get; set; }
        public Nullable<int> Risk_id4 { get; set; }
        public Nullable<int> Risk_id5 { get; set; }
        public Nullable<int> Risk_id6 { get; set; }
        public Nullable<int> Risk_id7 { get; set; }
        public Nullable<int> Risk_id8 { get; set; }
        public Nullable<int> Risk_id9 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TimeSheetTable> TimeSheetTable { get; set; }
        public virtual Risk Risk { get; set; }
    }
}
